# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tinvestido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
                ('image_url', models.CharField(blank=True, default=b'', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tinvestido',
            name='id_usuario',
            field=models.ForeignKey(db_column=b'id_usuario', on_delete=django.db.models.deletion.CASCADE, to='povmt.User'),
        ),
    ]
